name: 'Match a string against a regex pattern'
description: 'Match a string against a regex pattern and output its capture groups, if any.'
inputs:
  regex_pattern:
    description: "regex pattern"
    required: true
  regex_flags:
    description: "regex flags"
    required: false
  search_string:
    description: "search string"
    required: true
outputs:
  match_0:
    description: 'the first capture group of the match'
  match_1:
    description: 'the second capture group of the match'
runs:
  using: 'node12'
  main: 'index.js'